In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [100]:
data=pd.read_csv('MROZ.csv')
data.head(12)

inlf  hours  kidslt6  kidsge6  age  educ    wage  repwage  hushrs  husage  \
0      1   1610        1        0   32    12  3.3540     2.65    2708      34   
1      1   1656        0        2   30    12  1.3889     2.65    2310      30   
2      1   1980        1        3   35    12  4.5455     4.04    3072      40   
3      1    456        0        3   34    12  1.0965     3.25    1920      53   
4      1   1568        1        2   31    14  4.5918     3.60    2000      32   
5      1   2032        0        0   54    12  4.7421     4.70    1040      57   
6      1   1440        0        2   37    16  8.3333     5.95    2670      37   
7      1   1020        0        0   54    12  7.8431     9.98    4120      53   
8      1   1458        0        2   48    12  2.1262     0.00    1995      52   
9      1   1600        0        2   39    12  4.6875     4.15    2100      43   
10     1   1969        0        1   33    12  4.0630     4.30    2450      34   
11     1   1960        0        1   42    11  4.5918     4.58    2375      47   

    ...  faminc     mtr  motheduc  fatheduc  unem  city  exper   nwifeinc  \
0   ...   16310  0.7215        12         7   5.0     0     14  10.910060   
1   ...   21800  0.6615         7         7  11.0     1      5  19.499981   
2   ...   21040  0.6915        12         7   5.0     0     15  12.039910   
3   ...    7300  0.7815         7         7   5.0     0      6   6.799996   
4   ...   27300  0.6215        12        14   9.5     1      7  20.100058   
5   ...   19495  0.6915        14         7   7.5     1     33   9.859054   
6   ...   21152  0.6915        14         7   5.0     0     11   9.152048   
7   ...   18900  0.6915         3         3   5.0     0     35  10.900038   
8   ...   20405  0.7515         7         7   3.0     0     24  17.305000   
9   ...   20425  0.6915         7         7   5.0     0     21  12.925000   
10  ...   32300  0.5815        12         3   5.0     0     15  24.299953   
11  ...   28700  0.6215        14         7   5.0     0     14  19.700071   

       lwage  expersq  
0   1.210154      196  
1   0.328512       25  
2   1.514138      225  
3   0.092123       36  
4   1.524272       49  
5   1.556480     1089  
6   2.120260      121  
7   2.059634     1225  
8   0.754336      576  
9   1.544899      441  
10  1.401922      225  
11  1.524272      196  

[12 rows x 22 columns]

In [41]:
data.columns

Index(['inlf', 'hours', 'kidslt6', 'kidsge6', 'age', 'educ', 'wage', 'repwage',
       'hushrs', 'husage', 'huseduc', 'huswage', 'faminc', 'mtr', 'motheduc',
       'fatheduc', 'unem', 'city', 'exper', 'nwifeinc', 'lwage', 'expersq'],
      dtype='object')

In [43]:
#
X=data[['educ','exper','expersq','kidslt6','kidsge6']]
X=sm.add_constant(X)
Y=np.log(data['wage'])
X

const  educ  exper  expersq  kidslt6  kidsge6
0      1.0    12     14      196        1        0
1      1.0    12      5       25        0        2
2      1.0    12     15      225        1        3
3      1.0    12      6       36        0        3
4      1.0    14      7       49        1        2
..     ...   ...    ...      ...      ...      ...
423    1.0    10      2        4        0        5
424    1.0    12     21      441        0        1
425    1.0    13     22      484        0        2
426    1.0    12     14      196        0        1
427    1.0    12      7       49        0        1

[428 rows x 6 columns]

In [61]:
beta_hat=np.linalg.inv(X.T@X)@(X.T@Y)
beta_hat

array([-0.48565048,  0.10796231,  0.04003412, -0.00080296, -0.05341785,
       -0.01246959])

In [108]:
n=len(Y)
k=6
e=Y-X@beta_hat
e

0      0.050576
1     -0.636543
2      0.375221
3     -0.891663
4      0.335913
         ...   
423    0.229545
424    0.384817
425    0.384389
426    0.025923
427    0.368168
Length: 428, dtype: float64

In [110]:
sig_square=(e.T@e)/(n-k)
sig_square

0.445549427563927

In [79]:
var=sig_square*np.linalg.inv((X.T@X)/n)
var

array([[ 1.95353723e+01, -1.11533434e+00, -4.70138272e-01,
         1.00192118e-02,  8.93940870e-02, -8.92880301e-01],
       [-1.11533434e+00,  8.84867957e-02, -4.59783869e-03,
         1.72189091e-04, -6.95579285e-02,  1.81192725e-02],
       [-4.70138272e-01, -4.59783869e-03,  7.63452197e-02,
        -2.12609839e-03,  3.88572028e-02,  1.96891989e-02],
       [ 1.00192118e-02,  1.72189091e-04, -2.12609839e-03,
         6.64595561e-05, -4.25630835e-04, -1.47115779e-05],
       [ 8.93940870e-02, -6.95579285e-02,  3.88572028e-02,
        -4.25630835e-04,  3.06842926e+00, -3.38510148e-02],
       [-8.92880301e-01,  1.81192725e-02,  1.96891989e-02,
        -1.47115779e-05, -3.38510148e-02,  3.07311084e-01]])

In [81]:
std_err=np.sqrt(np.diag(var)/n)
print('Standard errors of beta coefficients: ')
print(std_err)

Standard errors of beta coefficients: 
[0.21364314 0.01437862 0.01335577 0.00039405 0.08467129 0.02679583]


In [140]:
#Stage I

Y1=data['educ']
X1=data[['exper','expersq','kidslt6','kidsge6','motheduc','fatheduc']]
X1=sm.add_constant(X1)
X1

const  exper  expersq  kidslt6  kidsge6  motheduc  fatheduc
0      1.0     14      196        1        0        12         7
1      1.0      5       25        0        2         7         7
2      1.0     15      225        1        3        12         7
3      1.0      6       36        0        3         7         7
4      1.0      7       49        1        2        12        14
..     ...    ...      ...      ...      ...       ...       ...
423    1.0      2        4        0        5         7         7
424    1.0     21      441        0        1         7         7
425    1.0     22      484        0        2         7         7
426    1.0     14      196        0        1        12        16
427    1.0      7       49        0        1        12        12

[428 rows x 7 columns]

In [142]:
beta2_hat=np.linalg.inv(X1.T@X1)@(X1.T@Y1)
beta2_hat

array([ 9.32486193e+00,  4.29398398e-02, -1.06809389e-03,  6.52589952e-01,
       -1.52581236e-01,  1.60245239e-01,  1.79623914e-01])

In [114]:
n=len(Y1)
k1=7
e2=Y1-X1@beta2_hat
e2

0     -1.549574
1      0.413220
2     -1.103795
3      0.534610
4     -0.358209
         ...   
423   -1.022647
424    0.017928
425    1.173497
426   -2.361018
427   -1.498953
Length: 428, dtype: float64

In [144]:
s2=(e2.T@e2)/(n-k1)
s2

4.081248737210448

In [146]:
var1=s2*np.linalg.inv((X1.T@X1)/n)
var1

array([[ 9.34867524e+01, -4.71352504e+00,  1.00194792e-01,
        -5.46479304e+00, -6.67068907e+00, -2.47025083e+00,
        -2.02359688e+00],
       [-4.71352504e+00,  6.97560802e-01, -1.94239599e-02,
         3.27584191e-01,  1.88895263e-01, -1.23876709e-02,
        -5.33162699e-04],
       [ 1.00194792e-01, -1.94239599e-02,  6.08791796e-04,
        -3.12800752e-03, -2.58441380e-04,  5.03294027e-04,
         6.83713180e-04],
       [-5.46479304e+00,  3.27584191e-01, -3.12800752e-03,
         2.76773537e+01, -2.08505564e-01, -8.17063811e-02,
        -9.93198987e-02],
       [-6.67068907e+00,  1.88895263e-01, -2.58441380e-04,
        -2.08505564e-01,  2.82464589e+00, -8.68444338e-02,
         1.45714781e-01],
       [-2.47025083e+00, -1.23876709e-02,  5.03294027e-04,
        -8.17063811e-02, -8.68444338e-02,  5.44281569e-01,
        -2.82279887e-01],
       [-2.02359688e+00, -5.33162699e-04,  6.83713180e-04,
        -9.93198987e-02,  1.45714781e-01, -2.82279887e-01,
         4.8657414

In [148]:
#
std_err1=np.sqrt(np.diag(var1)/n)
print('Standard errors of alpha coefficients: ')
print(std_err1)

Standard errors of alpha coefficients: 
[0.46736174 0.04037097 0.00119265 0.25429651 0.08123817 0.03566071
 0.03371729]


In [150]:
#H0: alpha5=0, alpha6=0
#wald statistic

R=np.array([[0,0,0,0,0,1,0],[0,0,0,0,0,0,1]])
q=np.zeros(2)
w=(R@beta2_hat-q).T@np.linalg.inv(R@np.diag(np.diag(var1))@R.T)@(R@beta2_hat-q)
w

0.11348881268704

In [21]:
#wald statistic is small hai tooh ham wald static ko accept karenge 

In [152]:
#Stage II

educ_fitted=X1@beta2_hat
educ_fitted.head()

0    13.549574
1    11.586780
2    13.103795
3    11.465390
4    14.358209
dtype: float64

In [154]:
Xnew=data[['exper','expersq','kidslt6','kidsge6']]
Xnew['educ_fitted']=educ_fitted
Xnew=Xnew[['educ_fitted','exper','expersq','kidslt6','kidsge6']]
Xnew=sm.add_constant(Xnew)
Xnew

C:\Users\sumit\AppData\Local\Temp\ipykernel_44616\2191203303.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Xnew['educ_fitted']=educ_fitted


const  educ_fitted  exper  expersq  kidslt6  kidsge6
0      1.0    13.549574     14      196        1        0
1      1.0    11.586780      5       25        0        2
2      1.0    13.103795     15      225        1        3
3      1.0    11.465390      6       36        0        3
4      1.0    14.358209      7       49        1        2
..     ...          ...    ...      ...      ...      ...
423    1.0    11.022647      2        4        0        5
424    1.0    11.982072     21      441        0        1
425    1.0    11.826503     22      484        0        2
426    1.0    14.361018     14      196        0        1
427    1.0    13.498953      7       49        0        1

[428 rows x 6 columns]

In [156]:
b=np.linalg.inv(Xnew.T@Xnew)@(Xnew.T@Y)
b

array([ 0.12246335,  0.05971665,  0.042541  , -0.00089684, -0.01549278,
       -0.02234876])

In [158]:
n=len(Y)
k=6
ep=Y-Xnew@b
ep

0     -0.125745
1     -0.631461
2      0.255373
3     -0.870928
4      0.350733
         ...   
423    0.087577
424    0.355359
425    0.483592
426   -0.151051
427    0.246420
Length: 428, dtype: float64

In [130]:
s_2=(ep.T@ep)/(n-k)
s_2

0.5013818836135346

In [132]:
var2=s_2*np.linalg.inv((Xnew.T@Xnew)/n)
var2

array([[ 8.42039497e+01, -6.19146493e+00, -2.72554780e-01,
         1.66891171e-03,  3.98098781e+00, -2.01557879e+00],
       [-6.19146493e+00,  4.91209560e-01, -2.55236084e-02,
         9.55859310e-04, -3.86131277e-01,  1.00584045e-01],
       [-2.72554780e-01, -2.55236084e-02,  8.69695323e-02,
        -2.43212183e-03,  5.97229284e-02,  1.79895311e-02],
       [ 1.66891171e-03,  9.55859310e-04, -2.43212183e-03,
         7.62706805e-05, -1.07803525e-03,  1.39497214e-04],
       [ 3.98098781e+00, -3.86131277e-01,  5.97229284e-02,
        -1.07803525e-03,  3.69493964e+00, -1.01132215e-01],
       [-2.01557879e+00,  1.00584045e-01,  1.79895311e-02,
         1.39497214e-04, -1.01132215e-01,  3.62241907e-01]])

In [134]:
#
s_err=np.sqrt(np.diag(var2)/n)
print('Standard errors of new beta coefficients: ')
print(s_err)

Standard errors of new beta coefficients: 
[4.43551801e-01 3.38775130e-02 1.42548182e-02 4.22140409e-04
 9.29141353e-02 2.90922601e-02]


In [138]:
#
#H0: education is exogenous
#H1: education is endogenous

H=(beta[1]-b[1])/np.sqrt(var2[1,1]-var[1,1])
H
#Since |H|<1.96, null hypothesis ko accept karenge tooh education is exogenous hogi.

0.07602478170010905